create table client_offer(
  id BIGINT GENERATED BY DEFAULT as identity,
  login_client VARCHAR2(30),
  limit_money BIGINT,
  percent TINYINT
);

insert into client_offer(id,login_client,limit_money,percent) values (0,'demo',1000,10);
insert into client_offer(id,login_client,limit_money,percent) values (1,'administrator',15000,15);
insert into client_offer(id,login_client,limit_money,percent) values (2,'user1',20000,10);
insert into client_offer(id,login_client,limit_money,percent) values (3,'alex',3800,10);
insert into client_offer(id,login_client,limit_money,percent) values (4,'mollo',18000,10);